name: gino
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - pip:
    - asyncpg
    - sanic
    - tornado
    - aiohttp
    - sphinxcontrib-asyncio
    - sphinx-rtd-theme>=0.3.0
